version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:127214169103:task-definition/app-container-app-task:12"
        LoadBalancerInfo:
          ContainerName: "app-container"
          ContainerPort: 80

Hooks:
  BeforeInstall:
    - location: "scripts/install_dependencies.sh"
      timeout: 300
      runas: root
  AfterInstall:
    - location: "scripts/start_server.sh"
      timeout: 300
      runas: root
