version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Build started on `date`"
      - mkdir -p build_output
      - cp appspec.yml build_outp/
      - cp taskdef.json build_outp/
      - cp -r scripts build_outp/

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: build_outp
  discard-paths: no
