version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 127214169103.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - docker build -t node-app .
      - docker tag node-app:latest 127214169103.dkr.ecr.ap-south-1.amazonaws.com/node-app:latest
      - mkdir -p build_output
      - cp appspec.yaml build_output/
      - cp taskdef.json build_output/
      - cp -r scripts build_output/

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 127214169103.dkr.ecr.ap-south-1.amazonaws.com/node-app:latest
      - echo "Build and push completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: build_output
  discard-paths: no
